import openai
import os
import requests
import tempfile
import asyncio

from core.cartridges import addCartridge, update_cartridge_field
from file_handling.s3 import write_file, read_file

openai.api_key = os.getenv('OPENAI_API_KEY', default=None)


async def generate_images(prompts, sessionID, convoID, loadout):

    tasks = [generate_image(prompt, sessionID, convoID, loadout) for prompt in prompts]
    images = await asyncio.gather(*tasks)
    images_str = ', '.join(images)
    return images_str


async def generate_image(prompt, sessionID, convoID, loadout):

    loop = asyncio.get_event_loop()
    response = await loop.run_in_executor(None, lambda: openai.Image.create(
        prompt=prompt,
        n=1,
        size='1024x1024'
        ))
    
    image_url = response['data'][0]['url']
    print(f'Image URL: {image_url}')
    response = requests.get(image_url)
    
    name = prompt + '.png'
    cartVal = {
        'label' : name,
        # 'text' : str(transcriptions),
        'description' : 'Image generated by openAI with prompt: ' + prompt,
        'file' : name,
        'extension' : 'image/png',
        # 'media_url' : url,
        'type' : 'media',
        'enabled' : True,
    }

    cartKey = await addCartridge(cartVal, sessionID, loadout, convoID )
    url = await write_file(response.content, cartKey) 
    print(url)
    await update_cartridge_field({'sessionID': sessionID, 'cartKey' : cartKey, 'fields': {'media_url': url}}, convoID, loadout, True)

    return name
