import openai
import os
import requests
from cartridges import addCartridge, update_cartridge_field
from file_handling.s3 import write_file, read_file
import tempfile

openai.api_key = os.getenv('OPENAI_API_KEY', default=None)


async def generate_image(prompt, sessionID, loadout):

    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size='1024x1024'
        )
    
    image_url = response['data'][0]['url']
    print(f'Image URL: {image_url}')
    response = requests.get(image_url)
    
    name = prompt[0:20] + '.png'
    cartVal = {
        'label' : name,
        # 'text' : str(transcriptions),
        'description' : 'Image generated by openAI with prompt: ' + prompt,
        'file' : name,
        'extension' : 'image/png',
        # 'media_url' : url,
        'type' : 'media',
        'enabled' : True,
    }

    cartKey = await addCartridge(cartVal, sessionID, loadout )
    url = await write_file(response.content, cartKey) 
    print(url)
    await update_cartridge_field({'sessionID': sessionID, 'cartKey' : cartKey, 'fields': {'media_url': url}}, loadout, True)

    return name
