[phases.setup]
    nixPkgs = ["...", "nodejs", "redis", "ffmpeg", "libsm6","libxext6", "fontconfig", "imagemagick", "barlow"]

[phases.install]
    cmds = [
        'PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy',
        'pipenv run prisma generate',
        'pipenv run python -m nltk.downloader punkt',
        'pipenv run python -m nltk.downloader averaged_perceptron_tagger',
    ]

[start]
    cmd = "/bin/bash -c 'source ./startup.sh'"
