[phases.setup]
nixPkgs = ["...", "redis"]

[phases.install]
cmds = ['PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy','pipenv run prisma generate','pipenv run python -m nltk.downloader averaged_perceptron_tagger', 'pipenv run python -m nltk.downloader averaged_perceptron_tagger', 'redis-server']
[phases.build]

[start]
cmds = ['pipenv run python main.py']

