[phases.setup]
    nixPkgs = ["...", "nodejs", "redis"]

[variables]
    NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM='1'

[phases.install]
    cmds = [
        'PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy',
        'pipenv run prisma generate',

    ]

[start]
    cmd = "/bin/bash -c 'source ./startup.sh'"
